general.unexpected.server.error=Une erreur inattendue du serveur s'est produite
general.unexpected.operation.error=Une erreur inattendue s'est produite lors de l'exécution de l'opération - {0}
general.id.not.set=Les données d'entrée ne sont pas valides - La valeur d'ID de l'objet {0} n'est pas défini
general.object.already.exist=Impossible d'ajouter un objet de type {0} car un objet avec le même ID existe déjà
general.object.does.not.exist=Erreur lors de l'exécution de l'opération {0}, les données d'entrée ne sont pas valides - l'objet de type {0} avec l'ID / clé {1} n'existe pas
general.id.set.on.new.object=Les données d'entrée ne sont pas valides - La valeur d'ID ne peut pas être définie sur un nouvel objet